CREATE TABLE IF NOT EXISTS audit_event (
    journal_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    idempotency_key VARCHAR(200) PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload CLOB NOT NULL,
    result CLOB,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS result CLOB;
ALTER TABLE audit_event ADD COLUMN IF NOT EXISTS journal_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS ux_audit_event_journal_sequence ON audit_event(journal_sequence);
